### ISSUE TITLE
暑培2023-作业2-部署的网址提交

### ISSUE THREAD

**Issue by Hayao-1111** [sast-summer-training-2023/sast2023-web#1]
网址：[59.66.131.240:46521](http://59.66.131.240:46521)
完成的作业内容：Part 1, Part 2, Part 3
主要修改如下：
- HTML部分：修改原通知与公开课的文本内容、部分图片内容、页脚内容、登陆框的提示文字与登录按钮文字，移除了部分元素与超链接
- CSS部分：修改标题的字体大小与颜色，修改登陆框的位置
- Javascript部分：点击左上角LOGO图片、点击登陆框提交按钮或点击课程图片均会弹出提示框

提交人：孙鑫礼

**Comment by ljr040929** [comment]
网址：[59.66.131.240:46521](http://59.66.131.240:45821/)
完成的作业内容：Part 1, Part 2, Part 3
更改了按钮字体内容（html）和按钮颜色（css）
在username一栏里填入“Why jiujingkexie is the god”,再点击右侧按钮就可得到相应的code，并且会改变按钮字体的颜色
当然也可以直接点击按钮（js）
提交人：刘佳睿

**Comment by YfLi03** [comment]
已批阅. 9.

后续可以自行尝试一些稍复杂的 JavaScript 脚本，例如尝试用 js 操纵 DOM 上的元素～
