### ISSUE TITLE
暑培2023-作业2-部署的网址提交

### ISSUE THREAD

**Issue by TosMIC20** [sast-summer-training-2023/sast2023-web#10]
- 完成部分：Part1、2、3
- 提交链接：http://59.66.131.240:45886/
- 修改内容
     1. `HTML`：更改文字，链接等；
     2. `CSS`：更改banner图片；
     3. `JS`：更改按钮的功能，按下”原神，启动！“按钮后更改图片并弹出窗口显示Part1的code；

- 提交人：冉博涵

**Comment by YfLi03** [comment]
已批阅. 9.

可以尝试更多 CSS 方面的修改，另外下面的图片似乎挂了？
