### ISSUE TITLE
暑培2023-作业2-部署的网址提交

### ISSUE THREAD

**Issue by srhn225** [sast-summer-training-2023/sast2023-web#11]
网址：http://59.66.131.240:45666/
完成的作业内容：Part 1, Part 2, Part 3

修改内容：

HTML：修改了部分文字的内容
CSS：修改了网页字体的颜色和分割线
JS：点击显示Code按钮后会弹出含有 code 的提示框
提交人：张子申

**Comment by YfLi03** [comment]
已批阅. 9.

为什么你改的是我的个人主页而不是网络学堂🤔

另外保存或者部署的时候少了一些东西，所以显示出来效果比较简陋
