### ISSUE TITLE
暑培2023-作业2-部署的网址提交 

### ISSUE THREAD

**Issue by zhuhz22** [sast-summer-training-2023/sast2023-web#12]
完成部分：
    Part1、2、3
网址：
    http://59.66.131.240:45801/
功能：
    html:登录部分修改；具体栏目修改
    点击CODE栏目"CLick me to get the code "显示code
    js:点击click me 按钮并将光标悬停在其上可使其变为红色
    css:CODE栏目字体
提交人：
    朱泓舟

**Comment by YfLi03** [comment]
已批阅. 10.

不错~
