### ISSUE TITLE
暑培2023-作业2-部署的网址提交

### ISSUE THREAD

**Issue by wuyuhang05** [sast-summer-training-2023/sast2023-web#13]
完成部分: PARTI, II, III
网址:
[http://59.66.131.240:46321/](http://59.66.131.240:46321/)
主要功能:
输入课程名和学号，按下查询成绩后判断如果是某个学号就输出 F 并弹窗提示挂科，否则输出 A+
更改了学堂公告内容等

**Comment by YfLi03** [comment]
已批阅. 10.

这位同学 请不要卖菜 (bushi)
