### ISSUE TITLE
暑培2023-作业2-部署的网址提交

### ISSUE THREAD

**Issue by ahydchh** [sast-summer-training-2023/sast2023-web#14]
### 网址http://59.66.131.240:45711
- html: 修改了文字内容
- javascript: 输入任意用户名及密码再点击Get Code即可显示Code 之后点击Repeat it按钮可再次显示Code
- css: 文字改为楷体

> 提交人 迟浩瀚

**Comment by YfLi03** [comment]
已批阅. 10.

改变字体不错.
