### ISSUE TITLE
暑培2023-作业2-部署的网址提交

### ISSUE THREAD

**Issue by ZiyiGaoCN** [sast-summer-training-2023/sast2023-web#15]
完成部分: PARTI, II, III
网址:
http://59.66.131.240:45201/
主要功能:
更改了登录框内容以及css
点击登录会弹出框：元神，启动！
同时登陆框背景会变成红色，再点击会变成蓝色。

**Comment by YfLi03** [comment]
已批阅. 10.

这个大块红蓝有一种上个世纪网站的感觉(
