### ISSUE TITLE
暑培2023-作业2-清华云盘链接提交

### ISSUE THREAD

**Issue by Tsingshanyuan** [sast-summer-training-2023/sast2023-web#16]
网址：https://cloud.tsinghua.edu.cn/f/8766e6b5653744a8bf31/?dl=1
html：修改了公告内容
css：所有文字加粗
javascript：点击“查看Code”弹出Code，点击“登录 GO”弹出“无法登录！”
提交者：张子文

**Comment by YfLi03** [comment]
已批阅. 8.

后续可以尝试部署到服务器上、稍复杂的 JS 脚本~
