### ISSUE TITLE
暑培2023-作业2-部署的网址提交

### ISSUE THREAD

**Issue by AziiiKwiii** [sast-summer-training-2023/sast2023-web#17]
完成部分: PARTI, II, III

网址: 
http://59.66.131.240:46286/

I. html: 修改部分文字、图片内容
II. css: 调整部分文字颜色
III. js:  点击「Get code」获取Code捏

提交人: 余响

**Comment by YfLi03** [comment]
已批阅. 9.

校徽都变红了捏~ 后续可以尝试一些稍复杂的 JS 脚本
