### ISSUE TITLE
暑培2023-作业2-部署的网址提交

### ISSUE THREAD

**Issue by dddong22** [sast-summer-training-2023/sast2023-web#18]
完成部分: PARTI, II, III

网址:
http://59.66.131.240:46081/

加入mycode和三个按钮
单击“弹出提示框”按钮会弹出“我是提示框！”字样
单击“红”或“绿”按钮会使得mycode背景色改变

提交人: 郭昊东

**Comment by YfLi03** [comment]
已批阅. 10.

按钮样式有点复古，不过该有的功能都有了x
