### ISSUE TITLE
暑培2023-作业2-部署的网址提交

### ISSUE THREAD

**Issue by Hisiao** [sast-summer-training-2023/sast2023-web#19]
**完成部分:** PARTI, II, III
**网址:**
 http://59.66.131.240:45431/
**主要功能:**
html：增加图片，显示code； “学堂公告”一栏内容被修改

css：网站“学堂公告”和“校内公开课”的标题文字颜色修改为红色
JavaScript：对“登录 GO”按钮控件进行修改，点击后会跳出提示窗，之后鼠标移动到按钮上，按钮颜色发生改变

**Comment by YfLi03** [comment]
已批阅. 10.

后续可以自行尝试一些稍复杂的 js 脚本～
