### ISSUE TITLE
暑培2023-作业2-部署的网址提交

### ISSUE THREAD

**Issue by ljr040929** [sast-summer-training-2023/sast2023-web#2]
网址：http://59.66.131.240:45821/
完成部分：part 1-part 2-part 3
改变了按钮的文本内容（html的修改），改变了按钮颜色（css的修改）,
在按下按钮后会出现提示框（内含code）
在输入用户名(Why jiujingkexie is the god)后按下按钮会出现提示框，且按钮字体颜色发生变化（js的修改）
提交人：刘佳睿

**Comment by YfLi03** [comment]
已批阅. 10.

很有意思！
