### ISSUE TITLE
暑培2023-作业2-清华云盘链接提交

### ISSUE THREAD

**Issue by SyGl233** [sast-summer-training-2023/sast2023-web#20]
https://cloud.tsinghua.edu.cn/d/e743dbdb37e343c4b841/

完成部分：普通版 I II III

对网络学堂主界面的更改内容：
1.HTML部分：更改部分文字和图片
2.CSS部分：更改部分文字颜色
3.JavaScript部分：将“登录 GO”按钮改为“查看Code”，点击后弹窗显示code并改变页面内容

提交人：宋昊原

**Comment by YfLi03** [comment]
已批阅. 8.

内容很有趣～ 后续可以尝试部署到服务器上.
