### ISSUE TITLE
暑培2023-作业2-清华云盘链接提交

### ISSUE THREAD

**Issue by OscarZs** [sast-summer-training-2023/sast2023-web#21]
云盘链接：https://cloud.tsinghua.edu.cn/d/b6a983f53f3948c68c50/
完成部分：普通版 Ⅰ Ⅱ Ⅲ
1.HTML部分：修改了学堂公告部分，改为了code展示
2.css：将公告部分与code展示部分的位置上移
3.javascrip：点击code后会弹窗显示完整的code
提交者：钟帅 2021012573

不太会部署，用域名+端口名也打不开其他同学部署的内容，不知道是啥问题

**Comment by YfLi03** [comment]
已批阅. 7.

打不开别的同学部署内容是因为之前服务器意料之外重启了，现在大部分已经恢复正常了～

后续可以尝试部署，以及使用一些稍复杂的 js 脚本.

最后，02 赛高！（雾）
