### ISSUE TITLE
暑培2023-作业2-清华云盘链接提交

### ISSUE THREAD

**Issue by Qu-rance** [sast-summer-training-2023/sast2023-web#22]
- 云盘链接：https://cloud.tsinghua.edu.cn/f/9ee91413364c475ca4c5/
- 完成部分：普通版PART I II III
  - html部分：修改了公告栏内容
  - css部分：修改了部分文字的颜色和字体大小
  - javascript部分：点击按键“点击查看code"可以看到PART I的code；点击红色标题后，标题会变为绿色

提交人：邱忍耐

**Comment by YfLi03** [comment]
已批阅. 8.

后续可以尝试部署到服务器上～
