### ISSUE TITLE
暑培2023-作业2-部署的网址提交

### ISSUE THREAD

**Issue by Jacky-777** [sast-summer-training-2023/sast2023-web#24]
**完成部分：**
PART 1,2,3
**网址：**
http://59.66.131.240:45741/
**主要功能：**
html：去掉了密码输入框，将账号输入框改为Code显示框，将登录按钮改为显示Code按钮
css：改变了账号输入框的宽度
js：单击Code显示按钮显示Code

提交人：宋嘉玺

**Comment by YfLi03** [comment]
已批阅. 9.

后续可以自行尝试一些更加复杂的修改～
