### ISSUE TITLE
暑培2023-作业2-部署的网址提交

### ISSUE THREAD

**Issue by ljj21** [sast-summer-training-2023/sast2023-web#25]
完成部分：
PART 1,2,3
网址：
http://59.66.131.240:45071/
主要功能：
html：将 “学堂公告” 改为了 “酒井暑期培训”
css：将部分字体改为了宋体
js：单击“登录 Go”的按钮，会弹出code，按钮会变成红色，并显示“Hack”

提交人：刘嘉骥

**Comment by YfLi03** [comment]
已批阅. 10.

为什么大家都把按钮改成红色呢 🤔
