### ISSUE TITLE
暑培2023-作业2-清华云盘链接提交

### ISSUE THREAD

**Issue by conan432** [sast-summer-training-2023/sast2023-web#26]
**完成部分：**
PART 1,2,3
**清华云盘链接：**
https://cloud.tsinghua.edu.cn/f/854dfe632d754f8fb8db/
**主要功能：**
html：更改了“学堂公告”一栏的内容，该栏目中只显示了一条题为“暑培作业完成情况”的通知，其中有一个名为“查看详情”的按钮
css：改变了按钮的位置和颜色
js：点击“查看详情”会弹出带有code的提示框

**提交人：简国浩**

**Comment by YfLi03** [comment]
已批阅. 7.

后续可以尝试部署，或者进行一些更加复杂的修改～
