### ISSUE TITLE
暑培2023-作业2-清华云盘链接提交

### ISSUE THREAD

**Issue by ywang22THU** [sast-summer-training-2023/sast2023-web#27]
**完成部分：**
PART 1,2,3
**云盘链接：**
https://cloud.tsinghua.edu.cn/f/7afb1e87601f40059cc5/
**作业说明：**
html：修改了公告栏与小标题文字内容
css：修改了部分字体颜色
js：当点击“学堂公告”时会将“学堂公告”变为“原神启动”，点击“code is here”时会弹出Part1中的code

**Comment by YfLi03** [comment]
已批阅. 8.

后续可以尝试部署，或者自行做一些更加复杂的修改～
