### ISSUE TITLE
暑培2023-作业2-清华云盘链接提交

### ISSUE THREAD

**Issue by yuekx** [sast-summer-training-2023/sast2023-web#28]
完成部分：
PART 1,2,3
清华云盘链接：
https://cloud.tsinghua.edu.cn/d/843dcbda483c4e6a9197/
主要功能：
html：更改了”学堂公告“文字内容、”校内公开课“图片和文字内容
css：更改了”查看详情“文字颜色
js：点击左上角猫猫logo会弹出显示code的提示框

提交人：许玥

**Comment by YfLi03** [comment]
已批阅. 9.

好可爱！这么好的网站怎么不部署上去给大家欣赏一下呢 qwq
