### ISSUE TITLE
暑培2023-作业2-清华云盘链接提交

### ISSUE THREAD

**Issue by leverimmy** [sast-summer-training-2023/sast2023-web#29]
### 完成部分：
普通版-PART 1,2,3
### 清华云盘链接：
https://cloud.tsinghua.edu.cn/f/079fc2ab52304b0393f9/
### 主要功能：
- html：更改了”校内公开课“第一节课的图片和文字内容
- css：更改了”2021年网络学堂功能更新公告“文字颜色为红色
- js：点击“摸鱼学导论”课程图片，会弹出显示“赶快摸鱼！”的提示框

提交人：2022011223

**Comment by YfLi03** [comment]
已批阅. 7.

后续可以尝试部署，或者做一些更加复杂的修改～
