### ISSUE TITLE
暑培2023-作业2-部署的网址提交

### ISSUE THREAD

**Issue by shch-y** [sast-summer-training-2023/sast2023-web#3]
网址：http://59.66.131.240:45151/
完成部分：part 1-part 2-part 3
改变了通知栏的标题、颜色和内容（内含code）
点击提示栏会出现对话框
按下登陆按钮后会变黑
提交人：施程予

**Comment by YfLi03** [comment]
已批阅. 9.

后续可以自行尝试一些稍复杂的 JavaScript 脚本与 CSS 修改～
