### ISSUE TITLE
暑培2023-作业2-清华云盘链接提交

### ISSUE THREAD

**Issue by dufengfeng** [sast-summer-training-2023/sast2023-web#30]
### 完成部分
Part 1,2,3
### 清华云盘链接
https://cloud.tsinghua.edu.cn/f/e3bc2cdf0c9940dc8e4d/
### 主要功能
1、html：修改了学堂公告中的文本内容，去掉了一些超链接
2、css：调整文字的颜色
3、js：简单建立两个按钮联动的效果，即点击任意一个按钮，会使得另一按钮变红，该按钮变白
提交人：李晋蔚

**Comment by YfLi03** [comment]
已批阅. 8.

整体修改还挺有趣的，后续可以尝试一下部署～
