### ISSUE TITLE
暑培2023-作业2-清华云盘链接提交

### ISSUE THREAD

**Issue by Smiling-DK** [sast-summer-training-2023/sast2023-web#31]
### 完成部分
普通版 PART 1、2、3
### 清华云盘链接
https://cloud.tsinghua.edu.cn/d/5d663e9fae214774ad2b/
### 主要功能
* HTML：更改了“学堂公告”部分的内容
* CSS：更改了 .xuetang 类元素的样式（设置字体颜色为北大红 #8C1515）
* JS：增加了登录按钮的逻辑。当输入用户名 admin，密码 123456，并点击登录后显示 Code；否则，显示 Error。

提交人：刘登科

**Comment by YfLi03** [comment]
已批阅. 7.

后续可以尝试一些更加复杂的修改～
