### ISSUE TITLE
暑培2023-作业2-清华云盘链接提交

### ISSUE THREAD

**Issue by jiangzizi** [sast-summer-training-2023/sast2023-web#32]
### 普通part 123

##清华云盘链接
https://cloud.tsinghua.edu.cn/d/e7dc273499cb477381e2/

## 主要功能
- HTML修改了学堂公告内容
- CSS上使用boothtrap对按钮、显示栏等部分进行了美观上的改进
- JS增加了按钮，获取code
- 完善了url跳转，让页面更加可用

提交人：江大治

**Comment by YfLi03** [comment]
已批阅. 7.

尝试使用 bootstrap 很不错～ 不过可能在保存文件的时候缺失了一些东西，我这边并不能很顺畅地完整加载你的网页.
