### ISSUE TITLE
暑培2023-作业2-清华云盘链接提交

### ISSUE THREAD

**Issue by Chengumpp** [sast-summer-training-2023/sast2023-web#33]
完成部分：
普通版-PART 1,2

清华云盘链接：
https://cloud.tsinghua.edu.cn/d/7623844ca5d6408cb05f/

主要功能：
html：删去了校内公开课的最后一个
css：更改了”学堂公告“与“校内公开课”文字颜色为青色
js：点击登录会跳出code
提交人：陈甘

**Comment by YfLi03** [comment]
已批阅. 7.

后续可以自行尝试一些更加复杂的修改～
