### ISSUE TITLE
暑培2023-作业2-清华云盘链接提交

### ISSUE THREAD

**Issue by ethan-yucheng-pan** [sast-summer-training-2023/sast2023-web#35]
完成部分：
普通版

清华云盘链接：
https://cloud.tsinghua.edu.cn/d/fb2cdd4e45274a2fa8f5/

修改：
html：修改标题、图标与按钮文字
样式：将两个按钮长度修改为一致，且与上方文字对齐
js：点击蓝色按钮会跳出code
提交人：潘禹丞

**Comment by YfLi03** [comment]
已批阅. 8.

目前唯一一个修改了超时界面的，很不错👍
