### ISSUE TITLE
暑培2023-作业2-清华云盘链接提交

### ISSUE THREAD

**Issue by 137wljs** [sast-summer-training-2023/sast2023-web#36]
清华云盘链接：https://cloud.tsinghua.edu.cn/f/9687b04a78f54125b63e/

修改：
html: 修改原学堂公告部分文字
css: 修改暑培作业提交部分字体颜色
js: 点击查看code按钮跳出展示窗口

提交人：殷尧瑞

**Comment by YfLi03** [comment]
已批阅. 7.

后续可以自行尝试复杂一些的修改～
