### ISSUE TITLE
暑培2023-作业-清华云盘链接提交

### ISSUE THREAD

**Issue by loadPoint** [sast-summer-training-2023/sast2023-web#37]
马治斌

Part I

最终请求的响应体：

    {"success": "You have successfully completed the challenge!", "code": "61205254c586a8d795fef09a58dc5fe9b15a9efae2f5533c98ce0bd713f31eeb"}

Part II

我做的修改如下：

删除和修改了HTML，更改文本的内容为 PartI 的神秘代码

修改了 index-new.css 当中的 .not 和 .xuetang ，使得对应部分（我的神秘代码和后面的Notice这几个字）的颜色发生了改变(可以对照原版网络学堂)

修改了原来的 ’ 登录 ‘ 按钮，改成了 ’ 点我点我 ‘，点完之后会弹出通知，并且关闭通知后，网页上的神秘代码的字体会变为红色的 

Part III

清华云盘链接：

https://cloud.tsinghua.edu.cn/f/cfc57e09e1f84ee1ad62/

提高：

没有，似乎我不在 sudoer 里面？所以 nginx 用不了

**Comment by YfLi03** [comment]
已批阅. 7.

很简洁～ 怎么拿到可以 sudo 的账号请参考 linux 课程的讲义
