### ISSUE TITLE
暑培2023-作业2-清华云盘链接提交

### ISSUE THREAD

**Issue by zouzh22** [sast-summer-training-2023/sast2023-web#38]
本人信息：邹卓恒-计25-2022010839
链接：https://cloud.tsinghua.edu.cn/d/5e17ce1b45b349dcbab7/
part1所得code：1cd2ec9c8676b0bfd80fa9bde109dd26b1f7c20a340ae9e4aa62214668c9309e
自己目前还有几个问题：自己尝试上传链接后，发现即使选择全部下载，也要将jpg、css等文件点开一遍之后网页才可以正常显示，请问是正常的吗？就是说，呢在下载我的链接时，可能需要将各个jpg文件、css文件、js文件点开一遍之后html才能正常显示。
自己改动中输入用户名密码的部分使用了form，但action等没有写，因此不会存在信息外流。

**Comment by YfLi03** [comment]
已批阅. 7.

似乎是完全自己写了一个网络学堂首页面，比较勇👍

提的问题我没太看懂，我这边直接打开 html 基本正常.
