### ISSUE TITLE
暑培2023-作业2-部署的网址提交

### ISSUE THREAD

**Issue by Cuiunbo** [sast-summer-training-2023/sast2023-web#4]
- 完成 part 1 2 3
1. html -> 标题更改
2. css -> 颜色背景悬停效果等更改
3. js -> 添加按钮

- [部署网页](http://59.66.131.240:46546/)
- 提交人 : 崔竣博

**Comment by YfLi03** [comment]
已批阅. 9.

这个网络学堂很简洁～ 后续可以自行尝试一些稍复杂的 JavaScript 脚本，例如尝试用 js 操纵 DOM 上的元素.
