### ISSUE TITLE
暑培2023-作业2-清华云盘链接提交

### ISSUE THREAD

**Issue by FLOW2090** [sast-summer-training-2023/sast2023-web#41]
云盘：https://cloud.tsinghua.edu.cn/f/89c920929a784626a261/

修改html部分字体，修改css部分字体颜色，修改按键alert框

提交人：刘子恒

**Comment by YfLi03** [comment]
已批阅. 7.

挺可爱的，尤其是标题（雾）

凌晨两点提交，同学辛苦了!
