### ISSUE TITLE
暑培2023-作业2-部署的网址提交

### ISSUE THREAD

**Issue by A-sock-puppet** [sast-summer-training-2023/sast2023-web#5]
网址：[59.66.131.240:46276](http://59.66.131.240:46276/)
完成的作业内容：Part 1, Part 2, Part 3

修改内容：
- HTML：修改 “学堂公告” 字样为 “酒井暑培” 等
- CSS：修改密码框（即现在的 code 框）长度，调整部分内容布局等
- JavaScript：点击 `Copy it` 按钮后弹出含有 code 的提示框，并复制 code 至剪贴板，同时改变按钮字样至 `Copied!` 

提交人：芦锦森

**Comment by YfLi03** [comment]
已批阅. 10.

Copy to clipboard 很贴心，不过在我这边 (macOS, Safari) 并没有真的实现 Copy，不知道是不是兼容性不太好～
