### ISSUE TITLE
暑培2023-作业2-部署的网址提交

### ISSUE THREAD

**Issue by Bocchi7** [sast-summer-training-2023/sast2023-web#6]
[这是网址](http://59.66.131.240:46341/)

对原网页的改动包含：
- 一些显而易见的对文字的修改（html）
- 将下面课程名字和相应教师、院系居中输出（css）
- 输入用户名和密码之后点击登录会将某处文字改成用户名和密码（js）

避坑提醒：
- part1中最后一步看看网址是否漏了'/'
- part3出现404错误的，可能是因为nginx没有访问文件的权限（特别地，nginx对home目录没有访问权限）
  - 参考：https://gist.github.com/jhjguxin/6208474?permalink_comment_id=3606458
  - 感谢icera

**Comment by YfLi03** [comment]
已批阅. 10.

背景渐变很好看，不过点击按钮后的修改突然有一种审美下线的感觉（
