### ISSUE TITLE
暑培2023-作业2-部署的网址提交

### ISSUE THREAD

**Issue by chengsx21** [sast-summer-training-2023/sast2023-web#9]
# 暑培2023-作业2-部署的网址提交

> 2021010761 程思翔

![imágenes de fate.jpeg](https://s2.loli.net/2023/07/13/X4FbTBCtYmjscKr.jpg)

## 部署网址

这里是提交的[部署网址](http://59.66.131.240:45236/).

## 修改内容

+ `HTML`: 为**标题栏**添加了 favicon, 将**超链接**链接至《原神》官方网页, 修改**更新公告**、**课程资源**栏及其他网页内容.

+ `CSS`: 修改**公告框长度**, 调整部分**内容布局**.

+ `JS`: 点击**更新公告**及**课程资源**右侧的**更多**按钮, 弹出含有 `Code` 的提示框, 同时改变按钮**颜色**.

**Comment by YfLi03** [comment]
已批阅. 10.

优秀作业👍，大概是玩原神玩的
